language: node_js

node_js:
  - "0.11"
  - "0.10"

addons:
  code_climate:
    repo_token:

after_script:
  - npm install -g grunt-cli
  - npm install -g codeclimate-test-reporter
  - grunt coverage
  - cat coverage/lcov.info | codeclimate
